apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: clean-sorry-cypress
  # You will probably want to change the namespace.
  namespace: argo
  annotations:
    workflows.argoproj.io/description: >-
      This workflowTemplate contains a step that cleans Sorry Cypress test runs via the Sorry Cypress API.
      
      You can either set the number of days to retain or it will default to cleaning tests that are 100 days old from todays date.

      You will need to provide the URL that points to your Sorry Cypress API url.
    workflows.argoproj.io/maintainer: 'sendible.com'
    workflows.argoproj.io/version: '>= 3.0.0'
    workflows.argoproj.io/sorry-cypress-version: '>= v2.0.0'
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
        - name: clean-cypress
          template: clean-cypress
          arguments:
            parameters:
            # Adjust the values of these parameters according to your requirements.
              - name: run_days_to_keep
                value: "200"
              - name: sorry_cypress_api_url
                value: "http://api-sorry-cypress.sorry-cypress.svc.cluster.local"

  - name: clean-cypress
    inputs:
      parameters:
      - name: run_days_to_keep
      - name: sorry_cypress_api_url
    container:
      image: ghcr.io/sendible-labs/sorry-cypress-run-cleaner:stable
      imagePullPolicy: Always
      env:
        - name: run_days_to_keep
          value: "{{inputs.parameters.run_days_to_keep}}"
        - name: sorry_cypress_api_url
          value: "{{inputs.parameters.sorry_cypress_api_url}}"
      resources:
        requests:
          memory: 32Mi
          cpu: 50m
      #Fail workflow if still running after 20 minutes
      activeDeadlineSeconds: 1200

